---
title: "Adnormal Conversation Starters"
format: html
editor: visual
execute:
  echo: false
  warning: false
  message: false
  cache: true
  cache.lazy: false
---

```{r, include = FALSE}
library(tidyverse)
library(brms)
library(bayesplot)
library(tidybayes)

setwd("/Users/jaden/Documents/Intellectual Fun/blog/AdnormalConversationStarters")

survey <- read_csv("~/Documents/Intellectual Fun/blog/AdnormalConversationStarters/Novel Questions (Responses) - Form Responses 1.csv")

survey_tidy <- survey %>% 
  dplyr::select(-c(Timestamp)) %>% 
  rename_with(~ c("Laughter", "Peacocks", "Guys_intimidated", "AI_jobs", 
                  "Nurture_vs_nature", "Emotional_iq", "Future_charity", "Human_takeover", 
                  "Insurance", "Korean_bias", "Poor_entrepreneurs", "War_vs_disease",
                  "Bad_hot_actors", "AI_morals", "Dreams", "Pools"), 1:16) %>% 
  pivot_longer(cols = everything(),
               names_to = "q",
               values_to = "rating") %>% 
  mutate(q_ = as.factor(q))
```

Find the survey at [adnormal questions survey](https://forms.gle/T5R1izmKQY2n9ZVv9)


::: {.panel-tabset}



## Bayesian shrinkage

```{r, include = FALSE}
bayes_lm <- brms::brm(
  rating ~ q,  
  data = survey_tidy,
  prior = c(
    prior(normal(3.5, .5), class = Intercept),
    prior(normal(0, 0.2), class = b),  # heavily regularized.
    prior(exponential(1), class = sigma)
  ),
  chains = 4, iter = 2000, cores = 4,
  backend = "cmdstanr", silent = 2,
  file = "fits/lm.1"
)

bayes_ordinal_hierarchical <- brms::brm(
  rating ~ 1 + (1 | q),  
  data = survey_tidy,
  family = cumulative(link = "logit"),
  prior = c(
    # Global intercepts (cutpoints) 
    prior(normal(0, 1.5), class = Intercept),
    
    # Hierarchical variance - how much factor levels vary from grand mean
    prior(exponential(1), class = sd, group = q)
  ),
  chains = 4, iter = 2000, cores = 4,
  backend = "cmdstanr", silent = 2,
  file = "fits/ordinal_hierarchical"
)


```

::: {.panel-tabset}

### bayes results
```{r}
# The parameter names are likely in format: r_q[question,Intercept] 
# Let's get the actual names and create the lookup
post_draws <- as_draws_df(bayes_ordinal_hierarchical)
actual_param_names <- names(post_draws)[grepl("^r_q\\[", names(post_draws))]

# Create lookup table with correct parameter names
question_lookup <- tibble(
  param_name = actual_param_names,
  question_text = c("Last Job to be taken by AI?", "Will we have to code AI morals?", 
                   "Why are hot actors bad at acting?", "Do dreams serve evolution?", 
                   "Why gender gap in emotional IQ?", "Charity to the future > now?", 
                   "Why gender gap in intimidation?", "Why did humans beat chimps?", 
                   "Why is there no divorce insurance?", "Does North Korean bias rival our own?", 
                   "Why do we laugh when we trip?", "Will we solve nature vs nurture?", 
                   "Why do peacocks have a long tail?", "Will there be another pool-like amenity?",
                   "3rd world entrepreneurs > factory jobs?", "Why do we care about war over disease?")
)

# Get ordering by effect size
param_order <- post_draws %>%
  select(all_of(actual_param_names)) %>%
  summarise_all(median) %>%
  pivot_longer(everything(), names_to = "parameter", values_to = "median") %>%
  left_join(question_lookup, by = c("parameter" = "param_name")) %>%
  arrange((median))

# Plot with ordered and labeled axes (using 'variable' instead of 'pars')
mcmc_plot(bayes_ordinal_hierarchical, 
          variable = param_order$parameter,
          type = "intervals") +
  scale_y_discrete(labels = param_order$question_text) +
  labs(title = "Question Effects (Highest to Lowest)",
       x = "Effect on Rating Propensity (log-odds)")

```


### code

```{r, echo = TRUE}
bayes_ordinal_hierarchical <- brms::brm(
  rating ~ 1 + (1 | q),  
  data = survey_tidy,
  family = cumulative(link = "logit"),
  prior = c(
    # Global intercepts (cutpoints) 
    prior(normal(0, 1.5), class = Intercept),
    
    # Hierarchical variance - how much factor levels vary from grand mean
    prior(exponential(1), class = sd, group = q)
  ),
  chains = 4, iter = 2000, cores = 4,
  backend = "cmdstanr", silent = 2,
  file = "fits/ordinal_hierarchical"
)
```


:::

## Frequentist factor effects

```{r}


freq_lm <- lm(rating ~ q, data = survey_tidy)
summary(freq_lm)
#anova(freq_lm, data = survey_tidy)
#sigma(freq_lm) 
```

:::


See the GitHub source [here](https://github.com/probably-jaden/adnormal-conversation-starters).

